### ISSUE TITLE
Kut Package Manager

### ISSUE THREAD

**Issue by waterdrop-io** [blade-lang/blade#137]
I writing an package manager for your language. What informations are important on the package structure in your language ?

Cordialy

**Comment by Zuygui** [comment]
Hi @mcfriend99 .

Thank you for your answer and your indications concerning the structure of the packages. The **kut** project aims to become the official package manager for the language. I chose to write it in Rust for ease and speed of execution. The project will be built little by little to get a good result. The project (in development) can be found on my profile. 
I wish you a good evening.

Sincerely.
