### ISSUE TITLE
Package Manager?

### ISSUE THREAD

**Issue by srevrtt** [blade-lang/blade#138]
Hello. I am kind of curious, will there be a package manager for this programming language? Examples could be pip for Python, or Cargo for Rust. This could be a good step in making this language usable for a lot of people. If you want, I could add a PR or an entirely different repository for this. Although, I don't have a good name for the package manager or the packages.

**Comment by srevrtt** [comment]
Oh, nevermind. There is already a package manager. My apologies.

**Comment by mcfriend99** [comment]
Hi @srevrtt,

Have you checked out the official package manager &mdash; [Nyssa](https://nyssa.bladelang.com)?

I'll greatly appreciate your feedback.
