### ISSUE TITLE
Make Blade documentation self-hosted

### ISSUE THREAD

**Issue by mcfriend99** [blade-lang/blade#182]
This task intends to replace the existing [bladelang.org](bladelang.org) website with a new version that's completely built in Blade. Nyssa documentation and `Getting Started` link will also be effectively pointing to it as Nyssa documentation will now be hosted along with Blade.

**Comment by Visco33** [comment]
https://bladelang.com/ appears to be down, is this related?

**Comment by taivlam** [comment]
The website seems like it's been taken over and turned into a single page Polish language site that has a target audience for retirees, but then clicking on the only button leads to a free website building service called [`mobiri.se`](https://mobiri.se/).

According to Wayback Machine [captures](https://web.archive.org/web/20210801000000*/https://bladelang.com/), the [last time](https://web.archive.org/web/20231201062649/https://bladelang.com/) the site properly displayed Blade documentation was on December 1, 2023.

**Comment by mcfriend99** [comment]
> The website seems like it's been taken over and turned into a single page Polish language site that has a target audience for retirees, but then clicking on the only button leads to a free website building service called [`mobiri.se`](https://mobiri.se/).
> 
> According to Wayback Machine [captures](https://web.archive.org/web/20210801000000*/https://bladelang.com/), the [last time](https://web.archive.org/web/20231201062649/https://bladelang.com/) the site properly displayed Blade documentation was on December 1, 2023.

Hi

Thank you for the continued interest in this issue. 

Unfortunately I've been unable to host the site due to lack of funds and no sponsors for this project yet so I've really be unable to maintain the hosting.

I'll try my best to re-host the project as soon as I can.

(Any advice or suggestions are welcomed)

Regards.
