### ISSUE TITLE
Error 502, bad gateway: Failure to access bladelang.com

### ISSUE THREAD

**Issue by the1Riddle** [blade-lang/blade#189]
## Describe the bug

Was going through the repos readme file and as I wanted to take a look at the tutorials on the usage,
but I noted that the domain leads to a 502 error, indicating a temporary server issue.
This might probably need some attention investigating and resolving the necessary 
to restore access and functionality to the page.

## To Reproduce

1. Go to the readme of this repo under the [Usage section](https://github.com/blade-lang/blade#usage)
2. Click on the tutorials link

## Expected behavior

The link should instead redirect me to the tutorials page.

## Screenshots

![image](https://github.com/blade-lang/blade/assets/125451537/f1434222-f5b2-4549-b3fe-5e0c24b67c5a)

## Desktop (please complete the following information):

 - OS: Fedora Linux
 - Browser Firefox
 - 123.0 (64-bit)

**Comment by dragsbruh** [comment]
Now it has branding of Lazada or something with questionable pictures of girls and some sort of game slot thingy

**Comment by mcfriend99** [comment]
Hi

Thank you for the continued interest in this issue. 

Unfortunately I've been unable to host the site due to lack of funds and no sponsors for this project yet so I've really be unable to maintain the hosting.

I'll try my best to re-host the project as soon as I can.

(Any advice or suggestions are welcomed)

Regards.

**Comment by dragsbruh** [comment]
Respectable but could you remove the link from the repo info its kind of weird rn

**Comment by the1Riddle** [comment]
> Respectable but could you remove the link from the repo info its kind of weird rn

this is also a good idea, the link can be commented out from the Readme till the site is up again

**Comment by mcfriend99** [comment]
Thanks to the generous donation of someone following the project. We are now live again at [https://bladelang.org](https://bladelang.org). The public repository for Nyssa will be live soon as well.

**Comment by dragsbruh** [comment]
Nice! I hope this project gets popular

**Comment by mcfriend99** [comment]
Nyssa is live.
