### ISSUE TITLE
Inclusion of GNU getopt under LGPL v2.1 or later licenses means that whole project must comply with LGPL v2.1 restrictions

### ISSUE THREAD

**Issue by galexite** [blade-lang/blade#47]
Both `blade_getopt.c` and `blade_getopt.h` have file headers which show that they have been distributed under the LGPL v2.1 or later license. In the [CMakeLists.txt](https://github.com/blade-lang/blade/blob/main/CMakeLists.txt#L31) file, these files are statically linked to the blade binary. Therefore, the whole project falls under the terms of the LGPL v2.1 or later license.

To keep this project MIT only, these files must be removed entirely.

**Comment by galexite** [comment]
@mcfriend99 as only the POSIX-style `getopt` function is used, you can use getopt from a *BSD distribution, which has a similar license to MIT and you're already using a vendored PCRE which uses a 3-clause BSD license anyway. I'll put up a pull request soon. In the meantime, do you fancy setting up something like a Gitter chat room and linking it in the README? It would be quite helpful for short discussions and so on.

**Comment by mcfriend99** [comment]
Thanks @galexite. I'll look into setting up Gitter later today.

**Comment by galexite** [comment]
I've been working through it myself on a Windows machine, building with MinGW and MSVC. I'm most of the way there currently, and where possible, I've managed to find permissive alternatives for non-standard C procedures.
