### ISSUE TITLE
Linking with `blade_termios.h` in any form means whole project must comply with GPL v3 or later license conditions

### ISSUE THREAD

**Issue by galexite** [blade-lang/blade#48]
`blade_termios.h` has a file header which shows that it has been originally licensed under GPL v3.

This file must be removed to keep blade under the permissive conditions of the MIT license.

**Comment by mcfriend99** [comment]
Good catch.

It will be removed shortly and will be replaced with an hand authored `blade_termios.h`

**Comment by mcfriend99** [comment]
Just realised I have practically overwritten the original termWin project. I guess I didn't see it important then to remove the copyright and header guard. I also did a quick relabelling just in case it will give rise to any issue in the future.

**Comment by mcfriend99** [comment]
Does the file still look in breach of the GPL license??

**Comment by galexite** [comment]
It looks like the copyright header is now there, so it shouldn't be breaching the license (IANAL), but if you link with this file in anyway, because it is a GPLv3 project, the GPLv3 conditions apply to the project as a whole. I haven't (yet) found any alternative implementations of termios for Windows which has a permissive license.

**Comment by mcfriend99** [comment]
I don't see another way this file could be implemented as the termios compatibility are majorly definitions and function declarations. There is hardly any way to implement this without looking like this file one way or the other without deliberately dropping important functionality.

**Comment by mcfriend99** [comment]
I decided to get rid of `blade_termios.h` file completely. Meaning that on systems that don't provide a `<termios.h>` header by default, the `io.TTY` functions will be disabled.
