### ISSUE TITLE
Expose AST as a standard library module

### ISSUE THREAD

**Issue by galexite** [blade-lang/blade#53]
It would be useful to expose parsing Blade code as a standard library module for the purposes of writing utilities, generating documentation and a language server, for example.

**Comment by mcfriend99** [comment]
We can write an AST module for Blade.

Blade currently use a single pass compiler and as such has no AST representation, but supporting this at a module level is a great and welcomed idea. It will facilitate https://github.com/blade-lang/blade/projects/4.

**Comment by BenStigsen** [comment]
Creating documentation not only for Blade, but also for user-made modules would be nice with regular comments.
```js
/* doc
  prints the sum of `a` and `b`
*/
def add(a, b) {
  print(a + b)
}
```
```py
# doc prints the resulting value of `a` subtracted by `b`
def sub(a, b) {
  print(a + b)
}
```
Then the output could look like:

---

### def add(a, b)
prints the sum of `a` and `b`

### def sub(a, b)
prints the resulting value of `a` subtracted by `b`

---

This would allow anyone to add documentation to their own application / module very easily. It would also make it easy to create a tool that generates the documentation. It would also be familiar to devs, that are used to adding documentation with `///`.

**Comment by mcfriend99** [comment]
Done as part of #101
