### ISSUE TITLE
Import not working when running in dotted path

### ISSUE THREAD

**Issue by mcfriend99** [blade-lang/blade#60]
## Describe the bug
Whenever Blade is installed in a path with containing the `.` character (for example using the Autoinstall script), imports stop working.

## To Reproduce
1. Install Blade using the Autoinstall script for Linux and OSX
2. Launch the Blade REPL
3. Try to import any library.

## Expected behavior
Import should work properly whether the application directory contains `.`s in it's path or not.

## Additional context
This is due to how `merge_paths` in `src/pathinfo.c` currently works.

**Comment by Brian3647** [comment]
Extra suggestion: use `/` as separation for local modules.

For example:
```blade
import ./my_module
import ../module_in/other/folder
import global_module # (example: os)
```
