### ISSUE TITLE
Replacing `# comments` with `// comments`

### ISSUE THREAD

**Issue by BenStigsen** [blade-lang/blade#69]
Currently comments are being made like so:
```
# Hello World

/* 
Hello
There
World 
*/
```
This to me does not make sense. Not only is this inconsistent with languages like JS, C, Python and a whole bunch of other languages. But it's also a bit harder to remember.
My proposal is to use `// comment` instead as it makes switching to Blade easier. It's easier to remember, not only because of other languages, but also because one character less is used.

If this isn't going to be changed to `//` that is fine, but I do at least propose some more consistency between single line and multiline comments. In JS, C and many more languages this is the `/` character, since it is used for both single-line and multiline. In Lua this is `--`, etc...

**Comment by Ravii20** [comment]
Hmm, what i think is that when i define MACRO in c in (Ellipses IDE) and after define it let say 

#define Two              2

Now i want to add comment ( a good practice)

#define Two              2          this is 2

Now i will try to select the world "this is 2" and use short cut to comment what will happen that , 
Whole line will be commented like this 

//#define Two 2                     this is 2 

And using the below method it easy and convenience to comment/uncommte the code also,

#define Two  2                       /*this is 2*/

Hope this make sense.

**Comment by BenStigsen** [comment]
I don't mean C, I mean Blade.
`#` is used for single-line comments, not macros, as far as I can tell.

So it's like this weird mix of Python and JS commenting style, which is more complicated to switch to and remember.

**Comment by Ravii20** [comment]
Ok understood your point , just shared what comes first in my mind about this

**Comment by mcfriend99** [comment]
The `//` operator exists in Blade. 

```blade
%> 16 // 7
2
```

For this reason, Blade cannot use `//` for line comments.

Also, part of Blade's core principles is syntax simplicity. For anything that can be achieved with a shorter syntax without leading to verbose repetition of code, Blade always opt for that shorter syntax.

Single line comments starting with an `#` 
- Saves an extra character (`/`)
- Allows easy interoperability on systems that support sha-bang (`#!`)
- Allows us to use `//` for floor divisions which are supported by Blade.

Let me know if you have further reservations or questions.

**Comment by BenStigsen** [comment]
Yeah okay, this makes sense. In terms of syntax, I would prefer just flooring the result with a function call and use `//` for comments. But this is personal taste. 

This issue is very minor so it's not really that important. I was mainly curious why it wasn't using `//`, but now I'm not anymore :smile: 

***Unrelated to the issue:***
So far I really like the language (even though I have basically only looked at it). The syntax is familiar, direct and clean. Using this from C also seems simpler than something like Wren. I like your future goal of a GUI with this language.

I intend on contributing to this language at some point, as it very much seems to have removed a lot of what I didn't like about Python, while also including a lot of what I did like.
