### ISSUE TITLE
Generate documentation with comments

### ISSUE THREAD

**Issue by BenStigsen** [blade-lang/blade#70]
Creating documentation not only for Blade, but also for user-made modules would be nice with regular comments.
```js
/* doc
  prints the sum of `a` and `b`
*/
def add(a, b) {
  print(a + b)
}
```
```py
# doc prints the resulting value of `a` subtracted by `b`
def sub(a, b) {
  print(a + b)
}
```
Then the output could look like:

---

### def add(a, b)
prints the sum of `a` and `b`

### def sub(a, b)
prints the resulting value of `a` subtracted by `b`

---

This would allow anyone to add documentation to their own application / module very easily. It would also make it easy to create a tool that generates the documentation. This also groups documentation together with the specific code, making it easier to navigate and edit. It would also be familiar to devs, that are used to adding documentation with `///`.

For the documentation generator, I guess these comments could be added to a map / dictionary like so:
```js
{
  'def add(a, b)': 'prints the sum of `a` and `b`',
  'def sub(a, b)': 'prints the resulting value of `a` subtracted by `b`',
}
```
Where depending on the input flags, this dictionary can easily output the documentation in markdown, HTML, JSON or something completely else.

**Comment by mcfriend99** [comment]
I think #53 will enable easy supports for this feature. I'll be adding this to the list of task in [this](https://github.com/blade-lang/blade/projects/4) project.

**Comment by mcfriend99** [comment]
The implementation of this have been enabled by the `ast` module and a working implementation is currently in the [blade-docs](https://github.com/blade-lang/blade-docs) repository.
