### ISSUE TITLE
README code example

### ISSUE THREAD

**Issue by BenStigsen** [blade-lang/blade#71]
Often times what gets me and many other people to not look further into projects, is the lack of very minimal examples.
I think the README should contain a tiny example, so that people can get a feel for the language right away. Since the language is very small, it doesn't really make that much sense to have a hello world example.

I propose something like:
```py
def sum(numbers) {
    var result = 0

    for num in number {
        result += num
    }

    print(result)
}

sum([1, 2, 3, 4]) # this will print "10"
```
This presents the developer with information about:
- functions
  - defining functions
  - calling functions
  - function arguments
- variables
- for loops
- assignment
- printing
- arrays
- single-line comments

**Comment by mcfriend99** [comment]
I think this snippet does justice to a readme introduction to the language and will add to the first impression. Can you suggest the best place in the current README where you think this could be inserted??

Also, typo in line 4... `numbers` not `number`.

Better still, can you create a PR that adds the sample code into the README??

**Comment by BenStigsen** [comment]
Sure, I'm thinking right above the documentation title. Should I use the same syntax highlighting as in this issue or do you think it would be better, without or with another highlighting language?

**Comment by mcfriend99** [comment]
I think the syntax highlighting is ok pending the time when we merge Blade's rouge highlighter upstream for Github support.

**Comment by mcfriend99** [comment]
You may want to use `echo` statement instead of the `print()` function which doesn't add a newline at the end of printed text by default to allow people testing from the REPL get a similar result as the REPL will still go ahead and print the return value of `sum` which is `nil` after the 10, and output will look like `10nil`. Using `echo` statement will avoid the confusion.

**Comment by BenStigsen** [comment]
Perhaps string formatting could be shown at the same time? What do you think about:
`echo 'the sum is ${result}'`

**Comment by mcfriend99** [comment]
I like this idea. We should expand the example to include that. Thanks!
