### ISSUE TITLE
Complete development of TLS/SSL module

### ISSUE THREAD

**Issue by mcfriend99** [blade-lang/blade#88]

**Comment by Brian3647** [comment]
What is this module for?

**Comment by mcfriend99** [comment]
The http module currently lacks https support. This module will enable us build support for https in the library.

This module is to enable TLS/SSL features in Blade and will foster the development of a built-in package manager and server with TLS support as well.

This module should probably wrap the OpenSSL library as it is available natively on most OS.

**Comment by mcfriend99** [comment]
> What is this module for?
> 
> 

Thanks for reminding me that this task has no description

**Comment by mcfriend99** [comment]
At #114, a lot of this has been done. Just left with a couple new implementations and the SSL module will be ready for a pre-release.

**Comment by mcfriend99** [comment]
The SSL module is pretty stable now so I'll be closing this ticket. Any new additions will be considered a feature.
