### ISSUE TITLE
Double backslashes with a single backslash replacement fails

### ISSUE THREAD

**Issue by progamateur** [blade-lang/blade#92]
Windows 10 21H1
cmake version 3.21.4
VSC 2019 - 16.11.6 / MSVC v142 / kit SDK Windows 10 (10.0.19041.0)

try this script:
	
    var str = 'C:\\\\foo\\\\bar'

	print("'" + str + "'.replace('\\\\', '/') ->  ")
	echo str.replace('\\\\', '/')
	echo ""

	print("'" + str + "'.replace('\\\\', '.') ->  ")
	echo str.replace('\\\\', '.')
	echo ""

	print("'" + str + "'.replace('\\\\', '\\') ->  ")
	echo str.replace('\\\\', '\\')

result:

	'C:\\foo\\bar'.replace('\\', '/') ->  C://foo//bar

	'C:\\foo\\bar'.replace('\\', '.') ->  C:..foo..bar

	'C:\\foo\\bar'.replace('\\', '\') ->  Unhandled Exception: RegexError: bad escape sequence in replacement string
	  StackTrace:
	    File: bug_3.b, Line: 12, In: <script>

**Comment by mcfriend99** [comment]
That's a PCRE2 issue I'm still trying to find a solution to myself but haven't had the time to look deep into it. If you try `echo str.replace('\\\\', '\\\\')` (i.e. considering that `\` is also an escape sequence which causes `\\\\` to be equal to `\\` in Blade and PCRE2 where PCRE2 uses the first `\` represented here as `\\` as a sequence internally, it works.

I'll look more into it and see how to resolve this.

**Comment by mcfriend99** [comment]
I'll look at it soon and revert. An easier solution may just be to create `\\` as `\\` (instead of escaped `\`) at the language level, but that is a strong decision to make and has it's pros and cons.

**Comment by progamateur** [comment]
It's ok.

script:

    echo 'C:\\\\foo\\\\bar'
    echo 'C:\\\\foo\\\\bar'.replace('/\\\\\\\\/', '\\')

result:

    C:\\foo\\bar
    C:\foo\bar
