### ISSUE TITLE
A loop that creates a long list is unexpectedly interrupted

### ISSUE THREAD

**Issue by progamateur** [blade-lang/blade#96]
Windows 10 / 21H1
Blade 0.0.6 (latest)

The following script that creates a list of 'n' numbers breaks if 'n' is above 406

     def create_list(list_len) {
	     var list = []
	     echo "Trying to create a ${list_len}-elements list"
		     iter var j = 0; j < list_len; j++ {
			     list += [j]
		     }
	     echo "      list content: " + list[0] + ", " + list[1] + " ... " + list[-2] + ", " + list[-1]
    }
     
     var n = 500
     echo ""
     create_list(n);

    echo "\nEnd of script"

Result if 'n' equals 500:

     Trying to create a 500-elements list

Result if 'n' equals 400:

     Trying to create a 400-elements list
               list content: 0, 1 ... 398, 399

     End of script

**Comment by mcfriend99** [comment]
This looks like a GC error. I'll fix ASAP and revert.

**Comment by mcfriend99** [comment]
Kindly update and try again. I personally tested with this:

```js
def create_list(list_len) {
    var list = []
    echo "Trying to create a ${list_len}-elements list"
    iter var j = 0; j < list_len; j++ {
        list += [j]
    }
    echo "      list content: " + list[0] + ", " + list[1] + " ... " + list[-2] + ", " + list[-1]
}

var n = 60000
echo ""
create_list(n);

echo "\nEnd of script"
```

**Comment by progamateur** [comment]
It'ok now.
In fact I have a reference script that I use to evaluate a new language. It's the one I transcribed into blade and that gave me trouble with loops that handle long strings. Now that the blade script is complete, I just increased the data to be processed and the loops behave as expected. The results are identical to those obtained by the equivalent JS script.

**Comment by progamateur** [comment]
Only tested in MSVC-compiled blade

**Comment by mcfriend99** [comment]
Hi,

The same problem obviously existed on other OS. It was a really great catch. Thanks a lot.

Is it possible to contribute your tests site into the projects??

Simply making them available in the tests folder will go a long way. I can do the work of adding them to ctest myself.

Please create a PR for this if you're interested. It will really go a long way for the language.

Regards

**Comment by progamateur** [comment]
Well, actually my script is very specific. It is meant to process NOAA wind forecasts and I don't think it could contribute in a relevant way to the test part of the language. On the other hand, I have some general functions that I had to develop that could integrate the 'test' or 'examples' parts. For example functions to generate 2D and 3D lists:

    # ========== new2D_list
    def new2D_list(row, col, init) {
       var list = [[init] * col]
       iter var i = 1; i < row; i++ {
            list += [[init] * col]
       }
       return list
    }

    # ========== new3D_list
    def new3D_list(row, col, lay, init) {
        var list = [new2D_list(row, col, init)]
        iter var i = 1; i < lay; i++ {
            list += [new2D_list(row, col, init)]
        }
        return list
    }

    var list_2D = new2D_list(3, 5, '-')
    list_2D[0][0] = 0
    echo list_2D
    echo""

    var list_3D = new3D_list(3, 4, 2, '-')
    list_3D[0][0][0] = 0
    echo list_3D

Tell me if this could be interesting?
