### ISSUE TITLE
Two Error Handling examples failed

### ISSUE THREAD

**Issue by progamateur** [blade-lang/blade#98]
Windows 10 21H1
Blade v0.0.6/MSVC

The following error handling examples failed (https://bladelang.com/tutorial/error-handling).
Nothing is displayed.

    try {
        echo 'No exception'
    } finally {
        echo 'No catch occured!'
    }

    try {
        die Exception('No exception')
    } finally {
        echo 'I will still run'
    }

**Comment by mcfriend99** [comment]
I tried on Linux and OSX already and it works just fine. Looks like a bug for Windows. I'll look into it ASAP
